# Generated by Django 2.1.3 on 2018-12-04 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=400)),
                ('tipo', models.CharField(choices=[('BG', 'Bug'), ('DCDU', 'Det CDU'), ('DOC', 'Documentação'), ('SP', 'Suporte'), ('TS', 'Teste'), ('DS', 'Desing'), ('RE', 'Reunião'), ('PL', 'Planejamento'), ('EST', 'Estudo'), ('AL', 'Ánálise'), ('DF', 'Defeito')], default='BG', max_length=50)),
                ('status', models.CharField(choices=[('EM10', 'Em Andamento 10%'), ('EM20', 'Em Andamento 20%'), ('EM30', 'Em Andamento 30%'), ('EM40', 'Em Andamento 40%'), ('EM50', 'Em Andamento 50%'), ('EM60', 'Em Andamento 60%'), ('EM70', 'Em Andamento 70%'), ('EM80', 'Em Andamento 80%'), ('EM90', 'Em Andamento 90%'), ('FB', 'Feedback'), ('RESV', 'Resolvida'), ('FECH', 'FECHADA')], default='EM10', max_length=50)),
                ('prioridade', models.CharField(choices=[('BA', 'Baixa'), ('NORMAL', 'Normal'), ('ALT', 'Alta'), ('URG', 'Urgente'), ('IMD', 'Imediata')], default='NORMAL', max_length=50)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('horas_estimadas', models.PositiveIntegerField(null=True)),
                ('horas_gastas', models.PositiveIntegerField(blank=True, null=True)),
                ('atribuido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
