# Generated by Django 2.1.2 on 2018-10-28 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(max_length=400)),
                ('tipo', models.TextField(max_length=400)),
                ('prioridade', models.TextField(max_length=400)),
                ('situacao', models.TextField(max_length=400)),
                ('data_inicio', models.DateField(verbose_name=datetime.date.today)),
                ('data_fim', models.DateField()),
                ('horas_estimadas', models.CharField(max_length=40)),
                ('horas_gastas', models.CharField(max_length=40)),
            ],
        ),
    ]
