# Generated by Django 2.1.2 on 2018-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=400)),
                ('tipo', models.IntegerField(choices=[(1, 'Bug'), (2, 'Det CDU'), (3, 'Documentação'), (4, 'Suporte'), (5, 'Teste'), (6, 'Desing'), (7, 'Reunião'), (8, 'Planejamento'), (9, 'Estudo'), (10, 'Ánálise'), (11, 'Defeito')], default=1)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Imediata')], default=1)),
                ('situacao', models.IntegerField(choices=[(1, 'Em Andamento 10%'), (2, 'Em Andamento 20%'), (3, 'Em Andamento 30%'), (4, 'Em Andamento 40%'), (5, 'Em Andamento 50%'), (6, 'Em Andamento 60%'), (7, 'Em Andamento 70%'), (8, 'Em Andamento 80%'), (9, 'Em Andamento 90%'), (10, 'Feedback'), (11, 'Resolvida')], default=1)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('horas_estimadas', models.CharField(max_length=40)),
                ('horas_gastas', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
