# Generated by Django 2.1.2 on 2018-11-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='tipo',
        ),
    ]
