# Generated by Django 2.1.2 on 2018-10-28 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Início'),
        ),
    ]
