# Generated by Django 2.1.3 on 2018-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='atribuido',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('EM10', 'Em Andamento 10%'), ('EM20', 'Em Andamento 20%'), ('EM30', 'Em Andamento 30%'), ('EM40', 'Em Andamento 40%'), ('EM50', 'Em Andamento 50%'), ('EM60', 'Em Andamento 60%'), ('EM70', 'Em Andamento 70%'), ('EM80', 'Em Andamento 80%'), ('EM90', 'Em Andamento 90%'), ('FB', 'Feedback'), ('RESV', 'Resolvida'), ('FECH', 'Fechada')], default='EM10', max_length=50),
        ),
    ]
