# Generated by Django 2.1.2 on 2018-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20181028_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
