# Generated by Django 2.1.2 on 2018-10-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='descricao',
        ),
    ]
