# Generated by Django 2.1.3 on 2018-12-09 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181201_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_coordinator',
            field=models.BooleanField(default=False, help_text='Designado para usuarios do tipo Coordenador', verbose_name='Coordenador'),
        ),
    ]
