# Generated by Django 2.1.3 on 2018-12-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181201_1658'),
        ('estagios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Advisor'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Supervisor'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='Aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Student'),
        ),
    ]
