# Generated by Django 2.1.3 on 2018-12-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estagios', '0002_auto_20181208_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
