# Generated by Django 2.1.3 on 2018-12-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0003_estagio_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagio',
            name='matricula',
        ),
    ]
