# Generated by Django 2.1.3 on 2018-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0004_remove_estagio_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagio',
            old_name='Aluno',
            new_name='aluno',
        ),
        migrations.AddField(
            model_name='estagio',
            name='nome_estagio',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
